WebApplication/Models/Movie.cs
namespace WebApplication.Models
{
    public class Movie : BaseModel
    {
        public string Title { get; set; }
        
        public string Description { get; set; }
        
        public string Genre { get; set; }

        public string Published { get; set; }
        
        public double Price { get; set; }
        
        public string ThumbnailPath { get; set; }
    }
}

WebApplication/ViewModels/MovieViewModel.cs
using System.Collections.Generic;
using WebApplication.Models;

namespace WebApplication.ViewModels
{
    public class MovieViewModel
    {
        public MovieViewModel(Movie movie)
        {
            Id = movie.Id;
            Title = movie.Title;
            Description = movie.Description;
            Genre = movie.Genre;
            Published = movie.Published;
            Price = movie.Price;
            ThumbnailPath = movie.ThumbnailPath;
        }

        public MovieViewModel(Movie movie, IEnumerable<Actor> actors, Director director) : this(movie)
        {
            Actors = actors;
            Director = director;
        }

        public MovieViewModel(Movie movie, int boughtCount) : this(movie)
        {
            BoughtCount = boughtCount;
        }

        public string Id { get; set; }

        public string Title { get; set; }

        public string Description { get; set; }

        public string Genre { get; set; }

        public string Published { get; set; }

        public double Price { get; set; }

        public string ThumbnailPath { get; set; }

        public int BoughtCount { get; set; }
        
        public IEnumerable<Actor> Actors { get; set; }
        
        public Director Director { get; set; }
    }
}

WebApplication/Controllers/AdminController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebApplication.Database;
using WebApplication.Models;
using WebApplication.Utils;
using WebApplication.ViewModels;

namespace WebApplication.Controllers
{
    public class AdminController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly Connection _connection;

        public AdminController(ILogger<HomeController> logger, Connection connection)
        {
            _logger = logger;
            _connection = connection;
        }

        #region Pages

        public async Task<IActionResult> MoviesPage()
        {
            _logger.Log(LogLevel.Information, "Movies page");
            var movies = await _connection.GetAllOfLabel<Movie>();
            return View(new AdminMoviesPageModel(movies));
        }
        
        public async Task<IActionResult> DirectorsPage()
        {
            _logger.Log(LogLevel.Information, "Directors page");
            var directors = await _connection.GetAllOfLabel<Director>();
            return View(new AdminDirectorsPageModel(directors));
        }
        
        public async Task<IActionResult> ActorsPage()
        {
            _logger.Log(LogLevel.Information, "Actors page");
            var actors = await _connection.GetAllOfLabel<Actor>();
            return View(new AdminActorsPageModel(actors));
        }
        
        public async Task<IActionResult> UsersPage()
        {
            _logger.Log(LogLevel.Information, "Users page");
            var users = await _connection.GetAllOfLabel<User>();
            return View(new AdminUsersPageModel(users));
        }

        public IActionResult AddMoviePage()
        {
            return View();
        }
        
        public async Task<IActionResult> EditMoviePage(string id)
        {
            var movie = await _connection.Find<Movie>((Constants.Id, id));
            return View(movie);
        }
        
        public IActionResult AddDirectorPage()
        {
            return View();
        }
        
        public async Task<IActionResult> EditDirectorPage(string id)
        {
            var director = await _connection.Find<Director>((Constants.Id, id));
            return View(director);
        }
        
        public IActionResult AddActorPage()
        {
            return View();
        }
        
        public async Task<IActionResult> EditActorPage(string id)
        {
            var actor = await _connection.Find<Actor>((Constants.Id, id));
            return View(actor);
        }

        #endregion

        #region Operations

        [Route("admin/movie/add", Name = "AddMovie")]
        public async Task<IActionResult> AddMovie(Movie movie)
        {
            await _connection.Create(movie);
            return RedirectToAction(nameof(MoviesPage));
        }

        [Route("admin/movie/edit", Name = "EditMovie")]
        public async Task<IActionResult> EditMovie(Movie movie)
        {
            await _connection.Update(movie.Id, movie);
            return RedirectToAction(nameof(MoviesPage));
        }

        [Route("admin/movie/remove", Name = "RemoveMovie")]
        public async Task<IActionResult> RemoveMovie(string id)
        {
            var movie = await _connection.Find<Movie>((Constants.Id, id));
            await _connection.Delete(movie);
            return RedirectToAction(nameof(MoviesPage));
        }
        
        [Route("admin/director/add", Name = "AddDirector")]
        public async Task<IActionResult> AddDirector(Director director)
        {
            await _connection.Create(director);
            return RedirectToAction(nameof(DirectorsPage));
        }
        
        [Route("admin/director/edit", Name = "EditDirector")]
        public async Task<IActionResult> EditDirector(Director director)
        {
            await _connection.Update(director.Id, director);
            return RedirectToAction(nameof(DirectorsPage));
        }
        
        [Route("admin/director/remove", Name = "RemoveDirector")]
        public async Task<IActionResult> RemoveDirector(string id)
        {
            var director = await _connection.Find<Director>((Constants.Id, id));
            await _connection.Delete(director);
            return RedirectToAction(nameof(DirectorsPage));
        }

        [Route("admin/actor/add", Name = "AddActor")]
        public async Task<IActionResult> AddActor(Actor actor)
        {
            await _connection.Create(actor);
            return RedirectToAction(nameof(ActorsPage));
        }
        
        [Route("admin/actor/edit", Name = "EditActor")]
        public async Task<IActionResult> EditActor(Actor actor)
        {
            await _connection.Update(actor.Id, actor);
            return RedirectToAction(nameof(ActorsPage));
        }
        
        [Route("admin/actor/remove", Name = "RemoveActor")]
        public async Task<IActionResult> RemoveActor(string id)
        {
            var actor = await _connection.Find<Actor>((Constants.Id, id));
            await _connection.Delete(actor);
            return RedirectToAction(nameof(ActorsPage));
        }
        
        [Route("admin/user/remove", Name = "RemoveUser")]
        public async Task<IActionResult> RemoveUser(string id)
        {
            var user = await _connection.Find<User>((Constants.Id, id));
            await _connection.Delete(user);
            return RedirectToAction(nameof(UsersPage));
        }
        #endregion
    }
}

WebApplication/Controllers/MovieController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebApplication.Database;
using WebApplication.Models;
using WebApplication.Utils;
using WebApplication.ViewModels;

namespace WebApplication.Controllers
{
    public class MovieController : Controller
    {
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly ILogger<MovieController> _logger;
        private readonly Connection _connection;

        public MovieController(IHttpContextAccessor httpContextAccessor, ILogger<MovieController> logger,
            Connection connection)
        {
            _httpContextAccessor = httpContextAccessor;
            _logger = logger;
            _connection = connection;
        }

        [Route("/buy", Name = "BuyMovie")]
        public async Task<IActionResult> BuyMovie(string id)
        {
            var user = SessionUtil.GetUser(_httpContextAccessor);
            var movie = await _connection.Find<Movie>((Constants.Id, id));
            var relationships = await _connection.GetRelationshipsBetween(user, movie, Constants.BoughtLabel);
            if (relationships == null || !relationships.GetEnumerator().MoveNext())
                await _connection.CreateDirectedRelationship(user, movie, Constants.BoughtLabel);
            else
                _logger.Log(LogLevel.Information, $"User {user.Email} already has bought movie {movie.Title}!");

            return Redirect("/");
        }
        
        [Route("/movie/{id}", Name = "ShowMovie")]
        public async Task<IActionResult> ShowMovie(string id)
        {
            var movie = await _connection.Find<Movie>((Constants.Id, id));
            var actors = await _connection.FindAllByRelationship<Movie, Actor>(movie, Constants.StarredLabel);
            var director = (await _connection.FindAllByRelationship<Movie, Director>(movie, Constants.DirectedLabel))
                .FirstOrDefault();
            var movieViewModel = new MovieViewModel(movie, actors, director);
            return View(movieViewModel);
        }

    }
}

WebApplication/Views/Movie/ShowMovie.cshtml
@model WebApplication.ViewModels.MovieViewModel
<div class="container-fluid">
    <div class="row">
        <div id="cover" class="col-5">
            <img src="@Model.ThumbnailPath" class="img-thumbnail mx-auto d-block" alt="@Model.Title"/>
        </div>
        <div id="title" class="col-7">
            <div class="row">
                <div class="h3">@Model.Title</div>
            </div>
            <div class="row">
                <div class="h5">@Model.Published</div>
            </div>
            <div class="row">
                <div class="h5">Genre: @Model.Genre</div>
            </div>
            <div class="row">
                <div class="h5">
                    Actors: <br/>
                </div>
            </div>
            <div>
                @foreach (var actor in Model.Actors)
                {
                    <div>
                        <text>@actor.ToString()</text>
                    </div>
                }
            </div>
            <div class="row">
                <div class="h5">
                    <text>Director:</text>
                </div>
            </div>
            <div>
                @Model.Director.ToString()
            </div>
            <div class="row">
                <div class="h4">Price: $@Model.Price</div>
            </div>
            <div>
                <a asp-controller="Movie" asp-action="BuyMovie" asp-route-id="@Model.Id" class="btn-primary">Buy movie</a>
            </div>
        </div>
        <div class="container-fluid text-body justify-content-center mt-3">
            @Model.Description
        </div>
    </div>
</div>

WebApplication/Views/Movie/_ActorItemView.cshtml
@model Actor

<div class="container-fluid">
    <div>
        <p>@Model.Name @Model.Surname</p>
        <div id="buttons" class="row pl-1">
            <a asp-controller="Admin" asp-action="EditActorPage" asp-route-id="@Model.Id">
                <div class="col-6 mb-0">
                    Edit
                </div>
            </a>
            <a asp-controller="Admin" asp-action="RemoveActor" asp-route-id="@Model.Id">
                <div class="col-6 mb-0">
                    Delete
                </div>
            </a>
        </div>
    </div>
</div>

WebApplication/Views/Movie/_DirectorItemView.cshtml
@model Director

<div class="container-fluid">
    <div>
        <p>@Model.Name @Model.Surname</p>
        <div id="buttons" class="row pl-1">
            <a asp-controller="Admin" asp-action="EditDirectorPage" asp-route-id="@Model.Id">
                <div class="col-6 mb-0">
                    Edit
                </div>
            </a>
            <a asp-controller="Admin" asp-action="RemoveDirector" asp-route-id="@Model.Id">
                <div class="col-6 mb-0">
                    Delete
                </div>
            </a>
        </div>
    </div>
</div>

WebApplication/Views/Movie/_MovieItemView.cshtml
@model Movie

<div class="container-fluid">
    <div>
        <img src="@Model.ThumbnailPath" class="img-thumbnail mx-auto d-block" alt="@Model.Title"/>
        <div id="buttons" class="row pl-1">
            <a asp-controller="Admin" asp-action="EditMoviePage" asp-route-id="@Model.Id">
                <div class="col-6 mb-0">
                    Edit
                </div>
            </a>
            <a asp-controller="Admin" asp-action="RemoveMovie">
                <div class="col-6 mb-0">
                    usuń
                </div>
            </a>
        </div>
    </div>
</div>

WebApplication/Views/Movie/_NewActorItemView.cshtml
<div class="container">
    <a asp-controller="Admin" asp-action="AddActorPage">
        <div>
            <img
                src="https://fellowesza.co.za/wp-content/uploads/woocommerce-placeholder.png"
                class="img-thumbnail mx-auto d-block"
                alt="New movie placeholder"/>
        </div>
    </a>
</div>

WebApplication/Views/Movie/_NewDirectorItemView.cshtml
<div class="container">
    <a asp-controller="Admin" asp-action="AddDirectorPage">
        <div>
            <img
                src="https://fellowesza.co.za/wp-content/uploads/woocommerce-placeholder.png"
                class="img-thumbnail mx-auto d-block"
                alt="New movie placeholder"/>
        </div>
    </a>
</div>

WebApplication/Views/Movie/_NewMovieItemView.cshtml
<div class="container">
    <a asp-controller="Admin" asp-action="AddMoviePage">
        <div>
            <img
                src="https://fellowesza.co.za/wp-content/uploads/woocommerce-placeholder.png"
                class="img-thumbnail mx-auto d-block"
                alt="New movie placeholder"/>
        </div>
    </a>
</div>