WebApplication/Controllers/AdminController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebApplication.Database;
using WebApplication.Models;
using WebApplication.Utils;
using WebApplication.ViewModels;

namespace WebApplication.Controllers
{
    public class AdminController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly Connection _connection;

        public AdminController(ILogger<HomeController> logger, Connection connection)
        {
            _logger = logger;
            _connection = connection;
        }

        #region Pages

        public async Task<IActionResult> MoviesPage()
        {
            _logger.Log(LogLevel.Information, "Movies page");
            var movies = await _connection.GetAllOfLabel<Movie>();
            return View(new AdminMoviesPageModel(movies));
        }
        
        public async Task<IActionResult> DirectorsPage()
        {
            _logger.Log(LogLevel.Information, "Directors page");
            var directors = await _connection.GetAllOfLabel<Director>();
            return View(new AdminDirectorsPageModel(directors));
        }
        
        public async Task<IActionResult> ActorsPage()
        {
            _logger.Log(LogLevel.Information, "Actors page");
            var actors = await _connection.GetAllOfLabel<Actor>();
            return View(new AdminActorsPageModel(actors));
        }
        
        public async Task<IActionResult> UsersPage()
        {
            _logger.Log(LogLevel.Information, "Users page");
            var users = await _connection.GetAllOfLabel<User>();
            return View(new AdminUsersPageModel(users));
        }

        public IActionResult AddMoviePage()
        {
            return View();
        }
        
        public async Task<IActionResult> EditMoviePage(string id)
        {
            var movie = await _connection.Find<Movie>((Constants.Id, id));
            return View(movie);
        }
        
        public IActionResult AddDirectorPage()
        {
            return View();
        }
        
        public async Task<IActionResult> EditDirectorPage(string id)
        {
            var director = await _connection.Find<Director>((Constants.Id, id));
            return View(director);
        }
        
        public IActionResult AddActorPage()
        {
            return View();
        }
        
        public async Task<IActionResult> EditActorPage(string id)
        {
            var actor = await _connection.Find<Actor>((Constants.Id, id));
            return View(actor);
        }

        #endregion

        #region Operations

        [Route("admin/movie/add", Name = "AddMovie")]
        public async Task<IActionResult> AddMovie(Movie movie)
        {
            await _connection.Create(movie);
            return RedirectToAction(nameof(MoviesPage));
        }

        [Route("admin/movie/edit", Name = "EditMovie")]
        public async Task<IActionResult> EditMovie(Movie movie)
        {
            await _connection.Update(movie.Id, movie);
            return RedirectToAction(nameof(MoviesPage));
        }

        [Route("admin/movie/remove", Name = "RemoveMovie")]
        public async Task<IActionResult> RemoveMovie(string id)
        {
            var movie = await _connection.Find<Movie>((Constants.Id, id));
            await _connection.Delete(movie);
            return RedirectToAction(nameof(MoviesPage));
        }
        
        [Route("admin/director/add", Name = "AddDirector")]
        public async Task<IActionResult> AddDirector(Director director)
        {
            await _connection.Create(director);
            return RedirectToAction(nameof(DirectorsPage));
        }
        
        [Route("admin/director/edit", Name = "EditDirector")]
        public async Task<IActionResult> EditDirector(Director director)
        {
            await _connection.Update(director.Id, director);
            return RedirectToAction(nameof(DirectorsPage));
        }
        
        [Route("admin/director/remove", Name = "RemoveDirector")]
        public async Task<IActionResult> RemoveDirector(string id)
        {
            var director = await _connection.Find<Director>((Constants.Id, id));
            await _connection.Delete(director);
            return RedirectToAction(nameof(DirectorsPage));
        }

        [Route("admin/actor/add", Name = "AddActor")]
        public async Task<IActionResult> AddActor(Actor actor)
        {
            await _connection.Create(actor);
            return RedirectToAction(nameof(ActorsPage));
        }
        
        [Route("admin/actor/edit", Name = "EditActor")]
        public async Task<IActionResult> EditActor(Actor actor)
        {
            await _connection.Update(actor.Id, actor);
            return RedirectToAction(nameof(ActorsPage));
        }
        
        [Route("admin/actor/remove", Name = "RemoveActor")]
        public async Task<IActionResult> RemoveActor(string id)
        {
            var actor = await _connection.Find<Actor>((Constants.Id, id));
            await _connection.Delete(actor);
            return RedirectToAction(nameof(ActorsPage));
        }
        
        [Route("admin/user/remove", Name = "RemoveUser")]
        public async Task<IActionResult> RemoveUser(string id)
        {
            var user = await _connection.Find<User>((Constants.Id, id));
            await _connection.Delete(user);
            return RedirectToAction(nameof(UsersPage));
        }
        #endregion
    }
}

WebApplication/Controllers/UsersController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using WebApplication.Database;
using WebApplication.Models;
using WebApplication.Utils;
using WebApplication.ViewModels;

namespace WebApplication.Controllers
{
    public class UsersController : Controller
    {
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly ILogger<UsersController> _logger;
        private readonly Connection _connection;

        public ISession Session => _httpContextAccessor.HttpContext.Session;

        public UsersController(IHttpContextAccessor httpContextAccessor, ILogger<UsersController> logger,
            Connection connection)
        {
            _logger = logger;
            _connection = connection;
            _httpContextAccessor = httpContextAccessor;
        }

        [Route("registration", Name = "RegisterUser")]
        public async Task<IActionResult> RegisterUser(User user)
        {
            user.UserType = "User";
            var dbUser = await _connection.Find<User>((Constants.Email, user.Email));
            if (dbUser != null)
                return Redirect("/");

            await _connection.Create(user);
            return Redirect("/");
        }

        [Route("login", Name = "LoginUser")]
        public async Task<IActionResult> LoginUser(UserViewModel userViewModel)
        {
            var user = await _connection.Find<User>((Constants.Email, userViewModel.Email));
            if (user == default)
                return Redirect("/");

            if (user.Password != userViewModel.Password)
                return Redirect("/");

            Session.SetString("user", JsonConvert.SerializeObject(user));
            await Session.CommitAsync();
            return Redirect("/");
        }

        [Route("logout", Name = "LogoutUser")]
        public async Task<IActionResult> LogoutUser()
        {
            Session.Clear();
            await Session.CommitAsync();
            return Redirect("/");
        }
    }
}

WebApplication/Views/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using WebApplication.Utils
@inject IHttpContextAccessor HttpContextAccessor

@{
    var user = SessionUtil.GetUser(HttpContextAccessor);
    var isLoggedIn = user != null;
    var isAdmin = user?.UserType == "ADMIN";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - WebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    @if (isAdmin)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="MoviesPage">Movies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="DirectorsPage">Directors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="ActorsPage">Actors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="UsersPage">Users</a>
                        </li>
                    }
                    @if (isLoggedIn)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="LogoutUser">Logout</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2020 - WebApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>